####################################################################################################
###############################  BUILD CONFIGURATION  ##############################################
####################################################################################################
[build-system]
requires = [
  "setuptools>=77",
  "packaging>=24",
]
build-backend = "build_backend"
backend-path = ["."]


[tool.setuptools]
include-package-data = true
package-dir = { "" = "" }

[tool.setuptools.dynamic]
version = {attr = "tensorrt_bionemo.version.__version__"}
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = [".", "nv_deps/TensorRT-LLM"]
include = ["tensorrt_bionemo*", "tensorrt_llm_lite*"]
exclude = ["cpp*"]

[tool.setuptools.package-data]
"tensorrt_bionemo" = [
    "libs/*.so"
]

[project]
name = "tensorrt_bionemo"
description = "TensorRT BioNeMo: GPU accelerated framework for protein folding"
requires-python = ">=3.10,<4.0"
authors = [{ name = "NVIDIA-BioNeMo team" }]
readme = "README.md"
dynamic = ["dependencies", "version"]
license = "Apache-2.0"

[project.scripts]
trtbnm-build = "tensorrt_bionemo.commands.build:main"

####################################################################################################
###############################  LINTING, FORMATTING AND TESTING CONFIGURATION  ####################
####################################################################################################
[tool.autoflake]
in-place = true
remove_all_unused_imports = true
remove_unused_variables = true
