# ------------------------------------------------------------------------
# base image for trtbnm
#   (1) start with trtllm image
#   (2) add needed cuda deps
# -------------------------------------------------------------------------
ARG BASE_IMAGE=tensorrt-llm
ARG BASE_TAG=base
FROM ${BASE_IMAGE}:${BASE_TAG} AS install_cuda_deps_stage

# set environment variables not related to build args
ENV DOCKERFILE_TRTBNM_BASE='1'
ENV CUDA_HOME=/usr/local/cuda
ENV PATH="${CUDA_HOME}/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda-13.0/targets/x86_64-linux/lib:${LD_LIBRARY_PATH}"

# cuda-13.0 and cuda-13.1 toolkits are each incomplete.
#   Desirable for base image to have a complete cuda toolkit
#   Strategy 1 is described below to address:
#
#     ToDo: finda better way for this
#     The active CUDA toolkit (/usr/local/cuda -> 13.1) in the base image is a
#     partial/runtime install: it has the compiler + core runtime but is missing
#     the cublas dev headers/libs and the nvrtc dev symlink that CMake's
#     find_package(CUDAToolkit) needs to resolve CUDA_cublasLt_LIBRARY /
#     CUDA_nvrtc_LIBRARY at configure time. Install just those dev packages
#     (full cuda-toolkit-13-1 is ~6.8GB and drags in GUI deps we don't need).
RUN apt-get update && apt-get install -y --no-install-recommends \
    ccache \
    libcublas-13-1 \
    libcublas-dev-13-1 \
    cuda-nvrtc-dev-13-1 \
    && rm -rf /var/lib/apt/lists/* \
    && CUDA_LIB_DIR=/usr/local/cuda/targets/$(uname -m)-linux/lib \
    && CUDA_INC_DIR=/usr/local/cuda/targets/$(uname -m)-linux/include \
    && ls -l ${CUDA_LIB_DIR}/libcublas.so.13 \
             ${CUDA_LIB_DIR}/libcublasLt.so \
             ${CUDA_LIB_DIR}/libnvrtc.so \
             ${CUDA_INC_DIR}/cublasLt.h


