# syntax=docker/dockerfile:1
ARG BASE_FOR_DEV_IMAGE='<internal-registry>/tensorrt-llm:1.2.0_80649a8'
FROM ${BASE_FOR_DEV_IMAGE} AS base_for_dev_image

# Install git and ssh
RUN apt-get update && apt-get install -y \
    git \
    openssh-client \
    && rm -rf /var/lib/apt/lists/*

# Add the correct GitLab host with custom port
RUN mkdir -p /root/.ssh && \
    ssh-keyscan -p 12051 <internal-git-host> >> /root/.ssh/known_hosts

# Clone repo (using SSH mount)
RUN pip install --upgrade pip
RUN --mount=type=ssh \
    git clone <internal-repository> /workspace/tensorrt-bionemo \
    && cd /workspace/tensorrt-bionemo \
    && pip install --no-build-isolation -v -e .