# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import numpy as np
import pytest
import torch

from bionemo_ir.configs.base import BaseConfig
from bionemo_ir.data.parsers import InputParsed, MSAParsed
from bionemo_ir.data.schemas.basic import PolymerParsed
from bionemo_ir.pipeline.models.openfold2.feature_context import FeatureContextGenerator


class MockConfig(BaseConfig):
    """Mock config for testing"""

    enable_template: bool = True
    is_multimer: bool = False
    max_templates: int = 4


@pytest.fixture
def sample_sequence():
    return "MKTVRQERLKSIVRILERSKEPVSGAQLAEELSVSRQVIVQDIAYLRSLGYNIVATPRGYVLAGG"


@pytest.fixture
def sample_input_parsed(sample_sequence):
    polymer = PolymerParsed(
        polymer_type="protein",
        chain_id="A",
        sequence=sample_sequence,
        msas=None,
        templates=None,
    )
    return InputParsed(input_id="test_input", polymers=[polymer])


@pytest.fixture
def sample_input_parsed_with_msa(sample_sequence):
    msa = MSAParsed(
        sequences=[sample_sequence, sample_sequence.replace("M", "L")],
        raw=[sample_sequence, sample_sequence.replace("M", "L")],
        descriptions=["seq1", "seq2"],
    )
    polymer = PolymerParsed(
        polymer_type="protein",
        chain_id="A",
        sequence=sample_sequence,
        msas=[msa],
        templates=None,
    )
    return InputParsed(input_id="test_input", polymers=[polymer])


@pytest.fixture
def sample_multimer_input_parsed(sample_sequence):
    polymer = PolymerParsed(
        polymer_type="protein",
        chain_id=["A", "B"],
        sequence=sample_sequence,
        msas=None,
        paired_msas=None,
        templates=None,
    )
    return InputParsed(input_id="test_multimer", polymers=[polymer])


def assert_numpy_array_exact(actual, expected):
    assert actual.shape == expected.shape
    assert actual.dtype == expected.dtype
    assert np.array_equal(actual, expected)
    if not actual.dtype.hasobject:
        assert actual.tobytes() == expected.tobytes()


def assert_tensor_dict_exact(actual, expected):
    assert actual.keys() == expected.keys()
    for key in actual:
        assert actual[key].shape == expected[key].shape, key
        assert actual[key].dtype == expected[key].dtype, key
        assert torch.equal(actual[key], expected[key]), key


class TestFeatureContextGeneratorPrimary:
    """Tests for primary sequence features generated by FeatureContextGenerator"""

    def test_generates_aatype(self, sample_input_parsed, sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert "aatype" in result
        assert result["aatype"].shape[0] == len(sample_sequence)

    def test_generates_residue_index(self, sample_input_parsed, sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert "residue_index" in result
        assert result["residue_index"].shape[0] == len(sample_sequence)
        assert result["residue_index"][0] == 0
        assert result["residue_index"][-1] == len(sample_sequence) - 1

    def test_generates_seq_length(self, sample_input_parsed, sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert "seq_length" in result
        assert result["seq_length"].shape[0] == len(sample_sequence)
        assert torch.all(result["seq_length"] == len(sample_sequence))

    def test_generates_between_segment_residues(self, sample_input_parsed, sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert "between_segment_residues" in result
        assert result["between_segment_residues"].shape[0] == len(sample_sequence)
        assert torch.all(result["between_segment_residues"] == 0)

    def test_aatype_dtype(self, sample_input_parsed):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert result["aatype"].dtype == torch.int64

    def test_residue_index_dtype(self, sample_input_parsed):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert result["residue_index"].dtype == torch.int32


class TestFeatureContextGeneratorMSA:
    """Tests for MSA features generated by FeatureContextGenerator"""

    def test_generates_msa_from_provided_msas(self, sample_input_parsed_with_msa):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        assert "msa" in result
        assert "deletion_matrix" in result
        assert "num_alignments" in result

    def test_msa_shape(self, sample_input_parsed_with_msa, sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        assert result["msa"].shape[1] == len(sample_sequence)

    def test_creates_dummy_msa_when_none_provided(self, sample_input_parsed, sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert "msa" in result
        # When no MSA provided, it creates a dummy with just the query sequence
        assert result["msa"].shape[0] >= 1
        assert result["msa"].shape[1] == len(sample_sequence)

    def test_deletion_matrix_shape_matches_msa(self, sample_input_parsed_with_msa):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        assert result["deletion_matrix"].shape == result["msa"].shape

    def test_num_alignments_values(self, sample_input_parsed_with_msa, sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        num_seqs = result["msa"].shape[0]
        assert result["num_alignments"].shape[0] == len(sample_sequence)
        assert torch.all(result["num_alignments"] == num_seqs)

    def test_msa_dtype(self, sample_input_parsed_with_msa):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        assert result["msa"].dtype == torch.int32
        assert result["deletion_matrix"].dtype == torch.float32


class TestFeatureContextGeneratorTemplate:
    """Tests for template features generated by FeatureContextGenerator"""

    def test_generates_templates_when_enabled(self, sample_input_parsed, sample_sequence):
        config = MockConfig(enable_template=True)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert "template_aatype" in result
        assert "template_all_atom_mask" in result
        assert "template_all_atom_positions" in result
        assert "template_sum_probs" in result

    def test_empty_template_shapes(self, sample_input_parsed, sample_sequence):
        config = MockConfig(enable_template=True)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        n_res = len(sample_sequence)
        assert result["template_aatype"].shape[0] == 0
        assert result["template_aatype"].shape[1] == n_res
        assert result["template_all_atom_mask"].shape[0] == 0
        assert result["template_all_atom_mask"].shape[1] == n_res
        assert result["template_all_atom_positions"].shape[0] == 0
        assert result["template_all_atom_positions"].shape[1] == n_res

    def test_empty_template_dtypes(self, sample_input_parsed):
        config = MockConfig(enable_template=True)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert result["template_aatype"].dtype == torch.float32
        assert result["template_all_atom_mask"].dtype == torch.float32
        assert result["template_all_atom_positions"].dtype == torch.float32
        assert result["template_sum_probs"].dtype == torch.float32

    def test_monomer_no_template_exactly_uses_empty_template_features(self, sample_sequence):
        generator = FeatureContextGenerator(MockConfig(enable_template=True))

        context = generator.build_monomer_context(
            sample_sequence,
            chain_id="A",
            description="no_template",
            templates=None,
        )
        expected = generator.empty_template_feats(len(sample_sequence))

        assert {key for key in context if key.startswith("template_")} == set(expected)
        for key, expected_value in expected.items():
            assert_numpy_array_exact(context[key], expected_value)

    def test_multimer_no_template_retains_fixed_empty_padding(self, sample_multimer_input_parsed, sample_sequence):
        config = MockConfig(enable_template=True, is_multimer=True)
        result = FeatureContextGenerator(config)(sample_multimer_input_parsed)
        n_res = 2 * len(sample_sequence)

        assert result["template_aatype"].shape == (config.max_templates, n_res)
        assert result["template_aatype"].dtype == torch.int64
        assert torch.count_nonzero(result["template_aatype"]) == 0
        assert result["template_all_atom_mask"].shape == (config.max_templates, n_res, 37)
        assert result["template_all_atom_mask"].dtype == torch.float32
        assert torch.count_nonzero(result["template_all_atom_mask"]) == 0
        assert result["template_all_atom_positions"].shape == (config.max_templates, n_res, 37, 3)
        assert result["template_all_atom_positions"].dtype == torch.float32
        assert torch.count_nonzero(result["template_all_atom_positions"]) == 0
        assert result["is_template_present"].shape == ()
        assert result["is_template_present"].dtype == torch.bool
        assert result["is_template_present"].item() is False

    def test_no_templates_when_disabled(self, sample_input_parsed):
        config = MockConfig(enable_template=False)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        # When templates are disabled, template features should not be in result
        assert "template_aatype" not in result
        assert "template_all_atom_mask" not in result
        assert "template_all_atom_positions" not in result
        assert "template_sum_probs" not in result


class TestFeatureContextGeneratorIntegration:
    """Integration tests for FeatureContextGenerator"""

    def test_unified_context_produces_all_features(self, sample_input_parsed_with_msa, sample_sequence):
        config = MockConfig(enable_template=True)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        n_res = len(sample_sequence)
        # Check primary features
        assert result["aatype"].shape[0] == n_res
        assert result["residue_index"].shape[0] == n_res
        # Check MSA features
        assert result["msa"].shape[1] == n_res
        # Check template features
        assert result["template_aatype"].shape[1] == n_res

    def test_context_has_all_expected_keys(self, sample_input_parsed_with_msa):
        config = MockConfig(enable_template=True)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        expected_keys = [
            "aatype",
            "residue_index",
            "seq_length",
            "between_segment_residues",
            "msa",
            "deletion_matrix",
            "num_alignments",
            "template_aatype",
            "template_all_atom_mask",
            "template_all_atom_positions",
            "template_sum_probs",
        ]
        for key in expected_keys:
            assert key in result, f"Missing key: {key}"

    def test_context_without_templates(self, sample_input_parsed_with_msa):
        config = MockConfig(enable_template=False)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        # Check that primary and MSA features are present
        expected_keys = [
            "aatype",
            "residue_index",
            "seq_length",
            "between_segment_residues",
            "msa",
            "deletion_matrix",
            "num_alignments",
        ]
        for key in expected_keys:
            assert key in result, f"Missing key: {key}"

        # Check that template features are NOT present
        template_keys = [
            "template_aatype",
            "template_all_atom_mask",
            "template_all_atom_positions",
            "template_sum_probs",
        ]
        for key in template_keys:
            assert key not in result, f"Unexpected key: {key}"

    def test_all_tensor_outputs(self, sample_input_parsed_with_msa):
        config = MockConfig(enable_template=True)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        # All outputs should be torch tensors
        for key, value in result.items():
            assert isinstance(value, torch.Tensor), f"Feature {key} is not a tensor"

    def test_repeated_calls_do_not_mutate_feature_names_or_outputs(self, sample_input_parsed_with_msa):
        generator = FeatureContextGenerator(MockConfig(enable_template=True))
        feature_names = tuple(generator.unsupervised_features)

        first = generator(sample_input_parsed_with_msa)
        second = generator(sample_input_parsed_with_msa)

        assert tuple(generator.unsupervised_features) == feature_names
        assert_tensor_dict_exact(first, second)

    def test_multimer_scalar_chain_ids_do_not_mutate_parsed_input(self):
        parsed = InputParsed(
            input_id="scalar_multimer_chain_ids",
            polymers=[
                PolymerParsed(chain_id="A1", sequence="MR", msas=None, paired_msas=None),
                PolymerParsed(chain_id="B1", sequence="AA", msas=None, paired_msas=None),
            ],
        )
        generator = FeatureContextGenerator(MockConfig(is_multimer=True))

        first = generator(parsed)
        second = generator(parsed)

        assert [polymer["paired_msas"] for polymer in parsed["polymers"]] == [None, None]
        assert first["aatype"].shape == (4,)
        assert torch.equal(first["asym_id"], torch.tensor([1, 1, 2, 2]))
        assert_tensor_dict_exact(first, second)
