# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import pytest
import torch

from tensorrt_bionemo.configs.base import BaseConfig
from tensorrt_bionemo.data.parsers import InputParsed, MSAParsed
from tensorrt_bionemo.data.schemas.basic import PolymerParsed
from tensorrt_bionemo.pipeline.models.openfold2.feature_context import \
    FeatureContextGenerator


class MockConfig(BaseConfig):
    """Mock config for testing"""
    enable_template: bool = True
    is_multimer: bool = False


@pytest.fixture
def sample_sequence():
    return "MKTVRQERLKSIVRILERSKEPVSGAQLAEELSVSRQVIVQDIAYLRSLGYNIVATPRGYVLAGG"


@pytest.fixture
def sample_input_parsed(sample_sequence):
    polymer = PolymerParsed(
        polymer_type="protein",
        chain_id="A",
        sequence=sample_sequence,
        msas=None,
        templates=None,
    )
    return InputParsed(input_id="test_input", polymers=[polymer])


@pytest.fixture
def sample_input_parsed_with_msa(sample_sequence):
    msa = MSAParsed(
        sequences=[sample_sequence,
                   sample_sequence.replace("M", "L")],
        raw=[sample_sequence,
             sample_sequence.replace("M", "L")],
        descriptions=["seq1", "seq2"],
    )
    polymer = PolymerParsed(
        polymer_type="protein",
        chain_id="A",
        sequence=sample_sequence,
        msas=[msa],
        templates=None,
    )
    return InputParsed(input_id="test_input", polymers=[polymer])


class TestFeatureContextGeneratorPrimary:
    """Tests for primary sequence features generated by FeatureContextGenerator"""

    def test_generates_aatype(self, sample_input_parsed, sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert "aatype" in result
        assert result["aatype"].shape[0] == len(sample_sequence)

    def test_generates_residue_index(self, sample_input_parsed,
                                     sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert "residue_index" in result
        assert result["residue_index"].shape[0] == len(sample_sequence)
        assert result["residue_index"][0] == 0
        assert result["residue_index"][-1] == len(sample_sequence) - 1

    def test_generates_seq_length(self, sample_input_parsed, sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert "seq_length" in result
        assert result["seq_length"].shape[0] == len(sample_sequence)
        assert torch.all(result["seq_length"] == len(sample_sequence))

    def test_generates_between_segment_residues(self, sample_input_parsed,
                                                sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert "between_segment_residues" in result
        assert result["between_segment_residues"].shape[0] == len(
            sample_sequence)
        assert torch.all(result["between_segment_residues"] == 0)

    def test_aatype_dtype(self, sample_input_parsed):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert result["aatype"].dtype == torch.int64

    def test_residue_index_dtype(self, sample_input_parsed):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert result["residue_index"].dtype == torch.int32


class TestFeatureContextGeneratorMSA:
    """Tests for MSA features generated by FeatureContextGenerator"""

    def test_generates_msa_from_provided_msas(self,
                                              sample_input_parsed_with_msa):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        assert "msa" in result
        assert "deletion_matrix" in result
        assert "num_alignments" in result

    def test_msa_shape(self, sample_input_parsed_with_msa, sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        assert result["msa"].shape[1] == len(sample_sequence)

    def test_creates_dummy_msa_when_none_provided(self, sample_input_parsed,
                                                  sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert "msa" in result
        # When no MSA provided, it creates a dummy with just the query sequence
        assert result["msa"].shape[0] >= 1
        assert result["msa"].shape[1] == len(sample_sequence)

    def test_deletion_matrix_shape_matches_msa(self,
                                               sample_input_parsed_with_msa):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        assert result["deletion_matrix"].shape == result["msa"].shape

    def test_num_alignments_values(self, sample_input_parsed_with_msa,
                                   sample_sequence):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        num_seqs = result["msa"].shape[0]
        assert result["num_alignments"].shape[0] == len(sample_sequence)
        assert torch.all(result["num_alignments"] == num_seqs)

    def test_msa_dtype(self, sample_input_parsed_with_msa):
        config = MockConfig()
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        assert result["msa"].dtype == torch.int32
        assert result["deletion_matrix"].dtype == torch.float32


class TestFeatureContextGeneratorTemplate:
    """Tests for template features generated by FeatureContextGenerator"""

    def test_generates_templates_when_enabled(self, sample_input_parsed,
                                              sample_sequence):
        config = MockConfig(enable_template=True)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert "template_aatype" in result
        assert "template_all_atom_mask" in result
        assert "template_all_atom_positions" in result
        assert "template_sum_probs" in result

    def test_empty_template_shapes(self, sample_input_parsed, sample_sequence):
        config = MockConfig(enable_template=True)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        n_res = len(sample_sequence)
        assert result["template_aatype"].shape[0] == 0
        assert result["template_aatype"].shape[1] == n_res
        assert result["template_all_atom_mask"].shape[0] == 0
        assert result["template_all_atom_mask"].shape[1] == n_res
        assert result["template_all_atom_positions"].shape[0] == 0
        assert result["template_all_atom_positions"].shape[1] == n_res

    def test_empty_template_dtypes(self, sample_input_parsed):
        config = MockConfig(enable_template=True)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        assert result["template_aatype"].dtype == torch.float32
        assert result["template_all_atom_mask"].dtype == torch.float32
        assert result["template_all_atom_positions"].dtype == torch.float32
        assert result["template_sum_probs"].dtype == torch.float32

    def test_no_templates_when_disabled(self, sample_input_parsed):
        config = MockConfig(enable_template=False)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed)

        # When templates are disabled, template features should not be in result
        assert "template_aatype" not in result
        assert "template_all_atom_mask" not in result
        assert "template_all_atom_positions" not in result
        assert "template_sum_probs" not in result


class TestFeatureContextGeneratorIntegration:
    """Integration tests for FeatureContextGenerator"""

    def test_unified_context_produces_all_features(
            self, sample_input_parsed_with_msa, sample_sequence):
        config = MockConfig(enable_template=True)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        n_res = len(sample_sequence)
        # Check primary features
        assert result["aatype"].shape[0] == n_res
        assert result["residue_index"].shape[0] == n_res
        # Check MSA features
        assert result["msa"].shape[1] == n_res
        # Check template features
        assert result["template_aatype"].shape[1] == n_res

    def test_context_has_all_expected_keys(self, sample_input_parsed_with_msa):
        config = MockConfig(enable_template=True)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        expected_keys = [
            "aatype",
            "residue_index",
            "seq_length",
            "between_segment_residues",
            "msa",
            "deletion_matrix",
            "num_alignments",
            "template_aatype",
            "template_all_atom_mask",
            "template_all_atom_positions",
            "template_sum_probs",
        ]
        for key in expected_keys:
            assert key in result, f"Missing key: {key}"

    def test_context_without_templates(self, sample_input_parsed_with_msa):
        config = MockConfig(enable_template=False)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        # Check that primary and MSA features are present
        expected_keys = [
            "aatype",
            "residue_index",
            "seq_length",
            "between_segment_residues",
            "msa",
            "deletion_matrix",
            "num_alignments",
        ]
        for key in expected_keys:
            assert key in result, f"Missing key: {key}"

        # Check that template features are NOT present
        template_keys = [
            "template_aatype",
            "template_all_atom_mask",
            "template_all_atom_positions",
            "template_sum_probs",
        ]
        for key in template_keys:
            assert key not in result, f"Unexpected key: {key}"

    def test_all_tensor_outputs(self, sample_input_parsed_with_msa):
        config = MockConfig(enable_template=True)
        generator = FeatureContextGenerator(config)
        result = generator(sample_input_parsed_with_msa)

        # All outputs should be torch tensors
        for key, value in result.items():
            assert isinstance(value,
                              torch.Tensor), f"Feature {key} is not a tensor"
